name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Build the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          push: false
